
// ═══════════════════════════════════════════════════════════════════
// MINDMAP DATA — DBA Literature Review
// RQ: How do enterprises ensure AI agents act in line with organizational mandate?
// ═══════════════════════════════════════════════════════════════════

window.MINDMAP_DATA = {

BLOCKS: [
  {
    id: 'A',
    title: 'BLOCK A',
    subtitle: 'Organizational Control Theory',
    color: '#1E3A5F',
    cardColor: '#16304F',
    borderColor: '#2D5A8E',
    colIdx: 0,
    papers: [
      {
        id: 'ouchi79', tier: 'core', crossRef: true,
        title: 'A Conceptual Framework for the Design of Organizational Control Mechanisms',
        authors: 'Ouchi', year: 1979, journal: 'Management Science',
        what: 'Defines three control modes — behavior, output, and clan — as a contingency framework based on output measurability and goal congruence.',
        how: 'Provides the foundational vocabulary for how enterprises govern actors through rules, metrics, and norms — the starting point for governing AI agents.',
        why: 'Anchors Block A as the theoretical origin of the entire argument; everything downstream builds on this typology.',
      },
      {
        id: 'eisenhardt85', tier: 'core',
        title: 'Control: Organizational and Economic Approaches',
        authors: 'Eisenhardt', year: 1985, journal: 'Management Science',
        what: 'Integrates economic (agency theory) and organizational perspectives on control, emphasizing monitoring, incentive design, and information asymmetry.',
        how: 'Adds the economic framing of delegation and information costs, directly relevant to AI agent oversight design.',
        why: 'The companion anchor to Ouchi, adding the economic and monitoring dimension that informs the Oracle\'s intervention logic.',
      },
      {
        id: 'adlerBorys', tier: 'core', star: '⭐ THE PIVOT PAPER', crossRef: true,
        title: 'Two Types of Bureaucracy: Enabling and Coercive',
        authors: 'Adler & Borys', year: 1996, journal: 'Administrative Science Quarterly',
        what: 'Distinguishes enabling formalization (which supports judgment and leaves intentional gaps) from coercive formalization (which generates workarounds and compliance theater).',
        how: 'Directly grounds the thesis claim that the control gap is intentional design — the gap humans fill, and that AI agents cannot fill the same way.',
        why: 'THE pivot paper of the entire argument. Without this, the B→C transition has no theoretical foundation.',
      },
      {
        id: 'kirsch96', tier: 'core',
        title: 'Management of Complex Tasks in Organizations: Controlling the ISD Process',
        authors: 'Kirsch', year: 1996, journal: 'Organization Science',
        what: 'Applies OCT to IS development, reframing control modes around controller knowledge rather than task programmability.',
        how: 'Establishes the IS-specific lineage of OCT and shows how observability without interpretive competence fails — exactly the AI agent problem.',
        why: 'Closes the IS citation expectation in Block A; IS-trained committee members will look for this paper.',
      },
      {
        id: 'cardinal04', tier: 'core', crossRef: true,
        title: 'Balancing and Rebalancing in the Creation and Evolution of Organizational Control',
        authors: 'Cardinal, Sitkin & Long', year: 2004, journal: 'Organization Science',
        what: 'Provides a 10-year longitudinal account of how control systems evolve through imbalance, pendulum dynamics, and rebalancing crisis.',
        how: 'The rebalancing logic maps directly onto the Oracle\'s reversible intervention ladder and the mandate drift correction cycle.',
        why: 'The only longitudinal dynamic paper in Block A — shows controls are not static, which is essential for justifying a governor loop.',
      },
      {
        id: 'ouchi80', tier: 'strong',
        title: 'Markets, Bureaucracies, and Clans',
        authors: 'Ouchi', year: 1980, journal: 'Administrative Science Quarterly',
        what: 'Extends OCT into cultural/clan governance as an alternative to market and bureaucratic control.',
        how: 'Clan norms provide the "computable mandate" analog that AI agents lack access to — motivating the Enterprise Story.',
        why: 'Essential companion to Ouchi (1979), extending the typology into the governance space most relevant to AI agents.',
      },
      {
        id: 'controlTwoFns', tier: 'strong',
        title: 'Organizational Control: Two Functions',
        authors: 'Tannenbaum', year: 1962, journal: 'Administrative Science Quarterly',
        what: 'Distinguishes integrative vs. coercive control functions in organizational settings.',
        how: 'Provides vocabulary for dual-function control that maps onto Sentinel (monitoring) and Oracle (correction) roles.',
        why: 'Background theoretical support for the two-function architecture of the proposed contribution.',
      },
      {
        id: 'unfoldingControl', tier: 'strong',
        title: 'Unfolding of Control Mechanisms',
        authors: 'Kirsch et al.', year: 2010, journal: 'Organization Science',
        what: 'Shows how controls transmute and customize over time — controls are not static typologies.',
        how: 'Justifies the dynamic, versioned nature of the Enterprise Story artifact against a backdrop of static control theory.',
        why: 'Supports the argument that control systems must evolve — key to the ratification loop design.',
      },
      {
        id: 'portfoliosIS', tier: 'strong',
        title: 'Portfolios of Control in Outsourced IS Projects',
        authors: 'Choudhury & Sabherwal', year: 2003, journal: 'Information Systems Research',
        what: 'Operationalizes OCT in IS outsourcing contexts with empirical evidence of control portfolio evolution.',
        how: 'IS-field empirical grounding for OCT application in technology governance contexts.',
        why: 'Provides IS-specific empirical support — important for committee members with IS backgrounds.',
      },
      {
        id: 'clanControlIT', tier: 'strong',
        title: 'Enacting Clan Control in Complex IT Projects',
        authors: 'Henderson & Lee', year: 1992, journal: 'MIS Quarterly',
        what: 'Empirical evidence of clan control in complex IT projects — shows how shared norms govern ambiguous tasks.',
        how: 'Direct IS application showing clan control failures when actors lack socialization — directly analogous to AI agents.',
        why: 'Provides empirical grounding for the claim that AI agents cannot enact clan control.',
      },
      {
        id: 'clientISControl', tier: 'strong',
        title: 'Controlling IS Development Projects (Client View)',
        authors: 'Kirsch et al.', year: 2002, journal: 'Organization Science',
        what: 'Client-side IS control — applies OCT from the delegating party\'s perspective in IS projects.',
        how: 'Maps the enterprise-as-principal perspective that mirrors AI agent delegation contexts.',
        why: 'Closes the client-side IS control gap; parallel to enterprise governing AI agents.',
      },
      {
        id: 'structContingency', tier: 'background',
        title: 'Structural-Contingency Model',
        authors: 'Donaldson', year: 2001, journal: 'Sage Publications',
        what: 'Background structural determinants of control choice in organizations.',
        how: 'Provides structural context for why different organizations need different control portfolios.',
        why: 'Background theoretical scaffolding for contingency-based control design.',
      },
      {
        id: 'cramInfoSec', tier: 'background',
        title: 'Organizational Information Security Policies',
        authors: 'Cram et al.', year: 2017, journal: 'EJIS',
        what: 'Policy lifecycle as a mandate governance analog in information security contexts.',
        how: 'Information security policy parallels the Enterprise Story artifact lifecycle — versioned, ratified, enforced.',
        why: 'Background support for policy-as-mandate framing in IS security literature.',
      },
    ]
  },

  {
    id: 'B',
    title: 'BLOCK B',
    subtitle: 'Human Agency as Completion Mechanism',
    color: '#1B4332',
    cardColor: '#163829',
    borderColor: '#2D6B4A',
    colIdx: 1,
    papers: [
      {
        id: 'kellogg20', tier: 'core', star: '⭐ B/C BRIDGE', crossRef: true,
        title: 'Algorithms at Work: The New Contested Terrain of Control',
        authors: 'Kellogg, Valentine & Christin', year: 2020, journal: 'Academy of Management Annals',
        what: 'Shows how algorithmic control reshapes human agency through comprehensive monitoring, nudging, and replacement of discretionary judgment.',
        how: 'The bridge paper between Blocks B and C — demonstrates the mechanism by which algorithms displace the human completion of OCT controls.',
        why: 'The highest-impact paper in the library for the B→C argument; its position here signals the transition.',
      },
      {
        id: 'eisenhardt89', tier: 'core', crossRef: true,
        title: 'Agency Theory: An Assessment and Review',
        authors: 'Eisenhardt', year: 1989, journal: 'Management Science',
        what: 'Reviews and integrates agency theory, covering principal-agent relationships, information asymmetry, monitoring, and incentive alignment.',
        how: 'Provides the principal-agent framing that applies to AI delegation — when the agent is non-human, the theory\'s assumptions break.',
        why: 'The companion to Eisenhardt (1985); agency theory is the formal framework for AI delegation decisions.',
      },
      {
        id: 'faraj18', tier: 'core', star: '⭐ ENTERPRISE CONTEXT',
        title: 'Working and Organizing in the Age of the Learning Algorithm',
        authors: 'Faraj, Pachidi & Sayegh', year: 2018, journal: 'Information and Organization',
        what: 'Identifies four structural aspects of learning algorithms — black-boxed performance, comprehensive digitization, anticipatory quantification, hidden politics — reshaping work inside enterprises.',
        how: 'Provides the enterprise (non-gig) empirical basis for claiming algorithms displace human judgment in corporate settings.',
        why: 'Closes the framing risk; gig economy papers show mechanisms, this paper shows those mechanisms inside traditional organizations.',
      },
      {
        id: 'whenAI22', tier: 'core',
        title: 'When AI Becomes the Agent of the Firm',
        authors: 'Various', year: 2022, journal: 'MIS Quarterly',
        what: 'Applies agency theory to AI as an organizational actor, tracing the evolution from tool to agent.',
        how: 'Directly bridges agency theory to AI, showing what changes when the agent is non-human and lacks the capacity for self-interest.',
        why: 'Critical bridge paper making the AI-as-agent framing theoretically grounded in established IS literature.',
      },
      {
        id: 'riseMachines19', tier: 'core',
        title: 'Rise of the Machines — Delegating Decisions to Autonomous AI',
        authors: 'Shrestha et al.', year: 2019, journal: 'California Management Review',
        what: 'Conceptualizes what it means to delegate decisions to non-human agents with different cognitive architectures.',
        how: 'Provides the delegation framework for understanding AI agent mandate faithfulness requirements.',
        why: 'Establishes the conceptual vocabulary for AI delegation that the thesis extends.',
      },
      {
        id: 'algMgmt20', tier: 'core',
        title: 'Algorithmic Management: Edge Case to Center Stage',
        authors: 'Duggan et al.', year: 2020, journal: 'Human Resource Management Journal',
        what: 'Defines algorithmic management as a distinct governance regime replacing discretionary human management.',
        how: 'Shows how algorithmic management removes the human interpretive layer from organizational control.',
        why: 'The defining paper for the algorithmic management regime that Block C explores in depth.',
      },
      {
        id: 'workingAlg16', tier: 'strong',
        title: 'Working for an Algorithm: Power Asymmetries',
        authors: 'Rosenblat & Stark', year: 2016, journal: 'Big Data & Society',
        what: 'Power asymmetries that arise when humans work under algorithmic authority structures.',
        how: 'Demonstrates the human agency gap that emerges under algorithmic control — motivates the governance gap.',
        why: 'Strong empirical grounding for algorithmic authority asymmetry claims.',
      },
      {
        id: 'algCoworkers17', tier: 'strong',
        title: 'Algorithms as Co-workers',
        authors: 'Möhlmann & Zalmanson', year: 2017, journal: 'ICIS Proceedings',
        what: 'Examines human-algorithm role interactions and role ambiguity in hybrid work settings.',
        how: 'Role ambiguity under algorithmic authority maps onto the governance vacuum the thesis addresses.',
        why: 'Empirical support for human-AI role boundary issues in organizational contexts.',
      },
      {
        id: 'algOrgChart21', tier: 'strong',
        title: 'The Algorithm and the Org Chart',
        authors: 'Cameron et al.', year: 2021, journal: 'Work, Employment and Society',
        what: 'Algorithmic logic conflicts with organizational hierarchy in enterprise practice.',
        how: 'Shows how algorithmic authority creates governance conflicts with formal organizational structure.',
        why: 'Directly motivates the need for a governance artifact that bridges algorithmic and organizational logic.',
      },
      {
        id: 'controlSurv92', tier: 'strong',
        title: 'Control and Surveillance in Work Practice',
        authors: 'Sewell & Wilkinson', year: 1992, journal: 'Sociology',
        what: 'Paradoxes of algorithmic control on workers — visibility increases but discretion decreases.',
        how: 'Control paradox maps onto the Sentinel\'s evidence-gathering role vs. worker autonomy tradeoffs.',
        why: 'Classic control paradox paper that anticipates algorithmic surveillance dynamics.',
      },
      {
        id: 'puranam14', tier: 'background',
        title: "What's New About New Forms of Organizing",
        authors: 'Puranam, Alexy & Reitzig', year: 2014, journal: 'AMR',
        what: 'Organizing problems — task division, allocation, reward, information — when the actor is AI not human.',
        how: 'Provides the organizing-problems framework for understanding what changes when AI replaces human actors.',
        why: 'Background theoretical scaffolding for organizational design with AI agents.',
      },
    ]
  },

  {
    id: 'C',
    title: 'BLOCK C',
    subtitle: 'Algorithmic Control Disrupts Human Completion',
    color: '#3B1F5E',
    cardColor: '#30184F',
    borderColor: '#5B3490',
    colIdx: 2,
    papers: [
      {
        id: 'algGovModes', tier: 'core', star: '⭐ ANCHOR', crossRef: true,
        title: 'Algorithmic Governance: A Modes of Governance Approach',
        authors: 'Musiani', year: 2013, journal: 'Internet Policy Review',
        what: 'Maps the modes-of-governance framework onto algorithmic systems, showing how algorithms embody and enact different governance logics.',
        how: 'Directly operationalizes OCT modes within algorithmic systems — the bridge between OCT and AI agent governance.',
        why: 'The conceptual anchor of Block C; all other Block C papers extend or qualify this framework.',
      },
      {
        id: 'agenticAISurvey', tier: 'core', star: '⭐ ANCHOR', crossRef: true,
        title: 'Agentic AI: Autonomous Intelligence for Complex Goals',
        authors: 'Masterman et al.', year: 2024, journal: 'IEEE Access',
        what: 'Comprehensive survey defining the scope, capabilities, and governance challenges of autonomous AI agents pursuing complex goals.',
        how: 'Defines precisely what kind of AI system the thesis governs — agentic systems that plan, act, and adapt across extended task sequences.',
        why: 'Essential definitional anchor; without it, the scope of "AI agent" in the research question is unclear.',
      },
      {
        id: 'flawsOversight', tier: 'core', star: '⭐ KEY CRITIQUE', crossRef: true,
        title: 'The Flaws of Policies Requiring Human Oversight of Government Algorithms',
        authors: 'Danaher et al.', year: 2017, journal: 'Government Information Quarterly',
        what: 'Argues that human oversight policies are structurally flawed because they assume oversight capacity that does not exist in practice.',
        how: 'Directly critiques the naive "just add a human in the loop" solution — motivating the need for a designed governance mechanism.',
        why: 'The critique paper that closes Block C\'s argument that existing solutions are insufficient.',
      },
      {
        id: 'algLegit22', tier: 'strong',
        title: 'Algorithmic Control & Legitimacy (Gig Workers)',
        authors: 'Cameron & Rahman', year: 2022, journal: 'Administrative Science Quarterly',
        what: 'Legitimacy as a precondition for effective algorithmic control in gig economy settings.',
        how: 'Legitimacy framing applies to Enterprise Story ratification requirements — mandate must be legitimate to be followed.',
        why: 'Supports the constitutional ratification mechanism of the Enterprise Story.',
      },
      {
        id: 'procJustice19', tier: 'strong',
        title: 'Procedural Justice in Algorithmic Fairness',
        authors: 'Lee et al.', year: 2019, journal: 'ACM CHI',
        what: 'Fairness and transparency as governance dimensions for algorithmic decision-making.',
        how: 'Procedural justice requirements map onto the Evidence Packet transparency design in the Sentinel.',
        why: 'Provides fairness vocabulary for the Evidence Packet design.',
      },
      {
        id: 'algRecourse20', tier: 'strong',
        title: 'Algorithmic Recourse Survey',
        authors: 'Verma et al.', year: 2020, journal: 'ACM Computing Surveys',
        what: 'Recourse mechanisms as ex-post correction tools for algorithmic decisions.',
        how: 'Recourse logic maps onto the Oracle\'s reversible intervention ladder.',
        why: 'Technical vocabulary for the Oracle\'s correction mechanism design.',
      },
      {
        id: 'contestability23', tier: 'strong',
        title: 'Conceptualising Contestability in AI Governance',
        authors: 'Alfrink et al.', year: 2023, journal: 'AI & Society',
        what: 'Contestability as a governance lever for algorithmic decisions affecting stakeholders.',
        how: 'Contestability requirements justify the Human Governance Owner ratification authority.',
        why: 'Provides theoretical grounding for the contestability mechanisms in the proposed artifact.',
      },
      {
        id: 'aiMgmtHype21', tier: 'strong',
        title: 'AI Management Beyond the Hype',
        authors: 'Raisch & Krakowski', year: 2021, journal: 'Academy of Management Review',
        what: 'Co-constitution of AI and organizational context — AI and organizations mutually shape each other.',
        how: 'Co-constitution logic supports the versioned, evolving nature of the Enterprise Story artifact.',
        why: 'Provides dynamic co-evolution framing that justifies continuous Story versioning.',
      },
      {
        id: 'connWorkplace19', tier: 'strong',
        title: 'The Connected Workplace: AI Surveillance in Enterprise',
        authors: 'Zuboff', year: 2019, journal: 'Harvard Business Review',
        what: 'AI surveillance and datification in enterprise settings — the behavioral data economy within organizations.',
        how: 'Datification of behavior provides the evidential substrate for Sentinel Evidence Packets.',
        why: 'Contextualizes the surveillance infrastructure that makes Sentinel monitoring feasible.',
      },
      {
        id: 'algMgmtConseq20', tier: 'strong',
        title: 'Algorithmic Management: Work Organisation Consequences',
        authors: 'Veen et al.', year: 2020, journal: 'Work, Employment and Society',
        what: 'Work organisation impacts of algorithmic management — speed-up, deskilling, and reduced autonomy.',
        how: 'Documents the human-completing-control-gap displacement that is Block C\'s central argument.',
        why: 'Strong empirical evidence for the claim that algorithms displace human judgment in organizational control.',
      },
      { id: 'algHRM19', tier: 'background', title: 'Algorithmic HRM Control (Gig Economy)', authors: 'Wood et al.', year: 2019, journal: 'New Technology, Work and Employment', what: 'HRM control through algorithms in gig economy contexts.', how: 'Provides gig economy baseline for algorithmic control patterns.', why: 'Background empirical context for algorithmic control mechanisms.' },
      { id: 'algUber21', tier: 'background', title: 'Algorithmic Control & Uber Drivers (Technostress)', authors: 'Möhlmann et al.', year: 2021, journal: 'MIS Quarterly', what: 'Technostress effects of algorithmic control on gig workers.', how: 'Illustrates control pathologies at the human-algorithm boundary.', why: 'Background illustration of algorithmic control failure modes.' },
      { id: 'goodGig14', tier: 'background', title: 'Good Gig, Bad Gig', authors: 'Friedman', year: 2014, journal: 'Cambridge Journal of Economics', what: 'Differential outcomes of gig economy algorithmic governance.', how: 'Shows governance variation under algorithmic control regimes.', why: 'Background context for algorithmic control heterogeneity.' },
      { id: 'platformCap16', tier: 'background', title: "Platform-Capital's App-etite for Control", authors: 'Huws et al.', year: 2016, journal: 'Work Organisation, Labour & Globalisation', what: 'Platform capital\'s use of algorithms to extract value from labor.', how: 'Platform governance model shows extreme algorithmic control without human mediation.', why: 'Background economic context for algorithmic control deployment.' },
      { id: 'highStakes19', tier: 'background', title: 'High-Stakes ADM: Child Welfare Cases', authors: 'Brown et al.', year: 2019, journal: 'Big Data & Society', what: 'Automated decision-making in high-stakes child welfare contexts.', how: 'High-stakes ADM shows the governance failures the thesis addresses in enterprise contexts.', why: 'Background illustration of ADM governance failures in critical applications.' },
      { id: 'goodBadJob18', tier: 'background', title: 'Making of the Good Bad Job', authors: 'Shapiro', year: 2018, journal: 'Sociological Theory', what: 'Theoretical account of how algorithmic control creates paradoxical work experiences.', how: 'Paradox of algorithmic control maps onto the control gap the thesis addresses.', why: 'Background theoretical support for algorithmic control paradox claims.' },
    ]
  },

  {
    id: 'D',
    title: 'BLOCK D',
    subtitle: 'AI Governance, Audit & Proposed Contribution',
    color: '#5C1A1A',
    cardColor: '#4E1515',
    borderColor: '#8B2E2E',
    colIdx: 3,
    papers: [
      {
        id: 'mittelstadt19', tier: 'core', star: '⭐ THE GAP PAPER', crossRef: true,
        title: 'Principles Alone Cannot Guarantee Ethical AI',
        authors: 'Mittelstadt', year: 2019, journal: 'Nature Machine Intelligence',
        what: 'Argues that high-level AI ethics principles structurally fail to prevent harm because they lack operational translation mechanisms.',
        how: 'THE gap paper — establishes why principles-only approaches are insufficient and why an operational artifact is needed.',
        why: 'The single most important motivation paper in Block D; everything downstream responds to the gap this paper identifies.',
      },
      {
        id: 'morley20', tier: 'core',
        title: 'From What to How: AI Ethics Tools',
        authors: 'Morley et al.', year: 2020, journal: 'Science and Engineering Ethics',
        what: 'Reviews publicly available AI ethics tools and methods, mapping the gap between principled commitments and operational practice.',
        how: 'Confirms Mittelstadt\'s claim empirically by showing the tools landscape — useful but incomplete.',
        why: 'Pairs with Mittelstadt to give the principles-to-practices gap a comprehensive dual citation.',
      },
      {
        id: 'rahwan18', tier: 'core', star: '⭐ ANTECEDENT', crossRef: true,
        title: 'Society-in-the-Loop: Programming the Algorithmic Social Contract',
        authors: 'Rahwan', year: 2018, journal: 'Ethics and Information Technology',
        what: 'Proposes a framework for programming an algorithmic social contract between human stakeholders and AI systems.',
        how: 'The Enterprise Story IS Rahwan\'s social contract — made versioned, machine-addressable, and operationally auditable.',
        why: 'Provides the conceptual antecedent for the Enterprise Story artifact; the thesis operationalizes what Rahwan only frames.',
      },
      {
        id: 'novelli23', tier: 'core', crossRef: true,
        title: 'Accountability in AI: What It Is and How It Works',
        authors: 'Novelli, Taddeo & Floridi', year: 2023, journal: 'AI & Society',
        what: 'Defines accountability through a seven-feature architecture and four goals: compliance, report, oversight, enforcement.',
        how: 'The Sentinel\'s Evidence Packets operationalize the interrogation feature; the Oracle\'s intervention ladder operationalizes limitation of power.',
        why: 'Gives the proposed contribution\'s design elements a formal accountability vocabulary.',
      },
      {
        id: 'hevner04', tier: 'core', star: '⭐ DSR ANCHOR',
        title: 'Design Science in Information Systems Research',
        authors: 'Hevner et al.', year: 2004, journal: 'MIS Quarterly',
        what: 'Establishes Design Science Research as a legitimate IS research paradigm through three cycles (relevance, design, rigor) and seven guidelines.',
        how: 'The methodological paradigm within which the Enterprise Story artifact is designed, evaluated, and contributed.',
        why: 'The primary DSR authority; defines what it means to make a design contribution in IS research.',
      },
      {
        id: 'peffers07', tier: 'core', star: '⭐ DSR PROCESS',
        title: 'A Design Science Research Methodology for IS Research',
        authors: 'Peffers et al.', year: 2007, journal: 'Journal of MIS',
        what: 'Provides a six-step DSR process model from problem identification through evaluation and communication.',
        how: 'The process template for how the Enterprise Story is designed and the ALiEn methodology is constructed.',
        why: 'The DSR process anchor — pairs with Hevner et al. to justify the research methodology.',
      },
      {
        id: 'gregor13', tier: 'core', star: '⭐ CONTRIBUTION FRAMEWORK', crossRef: true,
        title: 'Positioning and Presenting DSR for Maximum Impact',
        authors: 'Gregor & Hevner', year: 2013, journal: 'MIS Quarterly',
        what: 'Provides a knowledge contribution framework with four quadrants (Routine Design, Improvement, Exaptation, Invention) for positioning DSR artifacts.',
        how: 'The Enterprise Story sits in the Exaptation quadrant — applying known constructs (OCT, accountability theory) to a new problem domain (AI agent mandate faithfulness).',
        why: 'Positions the thesis contribution with precision; allows the committee to evaluate the originality claim rigorously.',
      },
      {
        id: 'euAI24', tier: 'core', star: '⭐ REGULATORY MANDATE',
        title: 'EU AI Act (Regulation 2024/1689)',
        authors: 'European Parliament', year: 2024, journal: 'Official Journal of the EU',
        what: 'EU legislation establishing harmonised rules for AI systems, including risk-tiered accountability requirements for high-risk AI applications.',
        how: 'Creates the regulatory context within which enterprise AI agent governance is no longer optional — institutional mandate for operational accountability.',
        why: 'Grounds the thesis in the live regulatory environment, showing practical urgency beyond academic contribution.',
      },
      {
        id: 'opAIGov22', tier: 'strong',
        title: 'Operationalising AI Governance through Ethics-Based Auditing',
        authors: 'Floridi et al.', year: 2022, journal: 'AI & Society',
        what: 'Industry case of operationalizing AI governance through structured ethics-based audit processes.',
        how: 'Closest prior art to the Enterprise Story — defines the gap the thesis fills by going beyond audit to versioned mandate.',
        why: 'Provides the most direct comparison point for the thesis contribution\'s originality claim.',
      },
      {
        id: 'ethicsAudit21', tier: 'strong',
        title: 'Ethics-Based Auditing to Develop Trustworthy AI',
        authors: 'Mökander & Floridi', year: 2021, journal: 'Minds and Machines',
        what: 'Audit as the primary governance mechanism for AI trustworthiness in organizational settings.',
        how: 'Audit logic directly feeds into the Sentinel\'s Evidence Packet architecture.',
        why: 'Technical audit vocabulary that the Sentinel operationalizes in the proposed contribution.',
      },
      {
        id: 'auditingAI22', tier: 'strong',
        title: 'Auditing of AI: Legal, Ethical and Technical Approaches',
        authors: 'Koshiyama et al.', year: 2022, journal: 'AI Assurance',
        what: 'Multi-disciplinary audit dimensions spanning legal, ethical, and technical perspectives.',
        how: 'Multi-dimensional audit framework maps onto the Sentinel\'s multi-clause Evidence Packets.',
        why: 'Justifies the multi-dimensional Evidence Packet design in the proposed contribution.',
      },
      {
        id: 'govAISafety20', tier: 'strong',
        title: 'Governing AI Safety through Independent Audits',
        authors: 'Brundage et al.', year: 2020, journal: 'arXiv',
        what: 'Independent audit as a control mechanism for AI safety in high-stakes applications.',
        how: 'Independent audit logic informs the Oracle\'s independence from the AI agent being governed.',
        why: 'Establishes the independence principle that the Oracle embodies.',
      },
      {
        id: 'reviewableADM21', tier: 'strong',
        title: 'Reviewable Automated Decision-Making',
        authors: 'Cobbe et al.', year: 2021, journal: 'Computer Law & Security Review',
        what: 'Reviewability as a fundamental requirement for legitimate automated decision-making.',
        how: 'Reviewability → Evidence Packet concept; each packet makes AI decisions inspectable against Story clauses.',
        why: 'Legal basis for the reviewability requirement that Evidence Packets fulfill.',
      },
      {
        id: 'algImpact18', tier: 'strong',
        title: 'Algorithmic Impact Assessments and Accountability',
        authors: 'Reisman et al.', year: 2018, journal: 'AI Now Institute',
        what: 'Ex-ante accountability mechanisms through structured impact assessment for algorithmic systems.',
        how: 'Impact assessment as a pre-deployment governance tool parallels the Enterprise Story ratification process.',
        why: 'Provides the impact assessment vocabulary that complements the Story\'s runtime governance.',
      },
      {
        id: 'instDistrust22', tier: 'strong',
        title: 'Institutionalised Distrust and Human Oversight (EU AI Act)',
        authors: 'Munn', year: 2022, journal: 'AI & Society',
        what: 'Institutional design for human oversight — why formal distrust mechanisms are necessary for AI governance.',
        how: 'Institutionalized distrust logic justifies the Sentinel\'s independent monitoring role.',
        why: 'Regulatory theory support for the independent monitoring architecture of the Sentinel.',
      },
      {
        id: 'seeingToolkit21', tier: 'strong',
        title: 'Seeing Like a Toolkit: AI Ethics Gaps',
        authors: 'Metcalf et al.', year: 2021, journal: 'Proceedings of the ACM',
        what: 'Toolkits envision AI ethics but don\'t enforce it — the gap between tool availability and governance.',
        how: 'Directly motivates the Enterprise Story as an enforcement mechanism, not just a checklist.',
        why: 'Closes the "toolkit exists" objection by showing toolkits don\'t govern — mandates do.',
      },
      {
        id: 'respAIReality21', tier: 'strong',
        title: 'Where Responsible AI Meets Reality',
        authors: 'Rakova et al.', year: 2021, journal: 'CSCW',
        what: 'Practitioner perspectives on enablers and barriers for responsible AI in enterprise settings.',
        how: 'Real-world governance barriers motivate the machine-addressable mandate design choices.',
        why: 'Practitioner grounding for the design choices in the Enterprise Story artifact.',
      },
      {
        id: 'principlesAssur21', tier: 'strong',
        title: 'Principles-Based Ethics Assurance Pattern',
        authors: 'Ashmore et al.', year: 2021, journal: 'IEEE Software',
        what: 'Structured assurance arguments for AI systems — mapping principles to operational evidence.',
        how: 'Assurance argument pattern directly informs the Story-clause to Evidence-Packet mapping.',
        why: 'Technical assurance vocabulary that bridges principles and the Evidence Packet design.',
      },
      {
        id: 'adaptiveGov20', tier: 'strong',
        title: 'Adaptive Responsible AI Governance Framework',
        authors: 'Cihon et al.', year: 2020, journal: 'AI & Ethics',
        what: 'Adaptive governance for decentralized AI systems that evolve over time.',
        how: 'Adaptive governance logic directly informs the versioned Enterprise Story update mechanism.',
        why: 'Theoretical support for the dynamic, adaptive governance loop in the proposed contribution.',
      },
      {
        id: 'accountableAI17', tier: 'strong',
        title: 'Accountable AI — Holding Algorithms to Account',
        authors: 'Doshi-Velez et al.', year: 2017, journal: 'Science',
        what: 'Accountability mechanisms overview for AI systems — what it means to hold an algorithm accountable.',
        how: 'Accountability mechanisms map onto the four-component ALiEn governance loop.',
        why: 'Core accountability vocabulary for the ALiEn methodology design.',
      },
      {
        id: 'agenticEnterprise24', tier: 'strong',
        title: 'The Emerging Agentic Enterprise',
        authors: 'Various', year: 2024, journal: 'Harvard Business Review',
        what: 'Enterprise leadership challenges when AI agents become organizational actors at scale.',
        how: 'Directly addresses the governance vacuum the thesis fills from a practitioner perspective.',
        why: 'Management-facing motivation for the thesis — establishes enterprise urgency.',
      },
    ]
  }
],

CROSS_LINKS: [
  { from: 'ouchi79',      fromBlock: 'A', to: 'algGovModes',    toBlock: 'C', label: 'clan control → computable mandate' },
  { from: 'adlerBorys',  fromBlock: 'A', to: 'CONTRIB',         toBlock: 'X', label: 'intentional gap → Enterprise Story' },
  { from: 'cardinal04',  fromBlock: 'A', to: 'CONTRIB',         toBlock: 'X', label: 'rebalancing logic → intervention ladder' },
  { from: 'eisenhardt89',fromBlock: 'B', to: 'agenticAISurvey', toBlock: 'C', label: 'principal-agent → non-human agents' },
  { from: 'kellogg20',   fromBlock: 'B', to: 'algGovModes',    toBlock: 'C', label: 'algorithmic control replaces human judgment' },
  { from: 'flawsOversight',fromBlock:'C',to: 'CONTRIB',         toBlock: 'X', label: 'oversight insufficient → Sentinel design' },
  { from: 'rahwan18',    fromBlock: 'D', to: 'CONTRIB',         toBlock: 'X', label: 'social contract → computable & versioned' },
  { from: 'novelli23',   fromBlock: 'D', to: 'CONTRIB',         toBlock: 'X', label: 'accountability architecture → Sentinel/Oracle' },
  { from: 'gregor13',    fromBlock: 'D', to: 'CONTRIB',         toBlock: 'X', label: 'Exaptation quadrant positioning' },
],

BLOCK_ARROWS: [
  { label: 'OCT controls are intentionally incomplete (Adler & Borys 1996) — humans fill the residual gap' },
  { label: 'AI agents remove the human completer — no socialization, norms, or escalation' },
  { label: 'Gap requires a versioned, machine-addressable mandate artifact' },
  { label: 'Enterprise Story + ALiEn fills the governance vacuum' },
],

};
